image: node:8.1.1

pipelines:
  branches:
    master:
     - step:
        caches:
          - node
        script:
          - npm install
          - npm run lint
          - npm test
          - git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
